#!/bin/bash

#next rows to kill locally running bot
#not usable
#pkill -f youtubebot;
#./youtubebot.py;

#getting container name from .env
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | xargs)
else
    echo ".env file not found!"
    exit 1
fi

# Command to stop the running bot inside the container (if needed)
sudo docker exec $CONTAINER_NAME pkill -f youtubebot.py;

# Command to start the bot inside the container
sudo docker exec $CONTAINER_NAME python3 ./youtubebot.py;
