#!/bin/bash

#next rows to kill locally running bot
#note: needs procps to be installed on docker when running on docker, added installing it to buildAndRunDocker.sh
echo "force restarting bot"

pkill -f youtubebot.py

# Wait until the process is completely killed
while pgrep -f youtubebot.py > /dev/null; do
    echo "Waiting for youtubebot.py to terminate..."
    sleep 1
done

# Start the bot again
python3 ./youtubebot.py

